### ISSUE TITLE
Implement step to connect db

### ISSUE THREAD

**Issue by smallcreep** [smallcreep/seeds-cucumber#10]
Step Definition
```gherkin
Given The connection to the database name
```
This step should parse properties file and get connection from the [sections db](https://github.com/smallcreep/cucumber-seeds#%D0%A8%D0%B0%D0%B3%D0%B8-%D0%B4%D0%BB%D1%8F-db).
And check that DB is available.

**Comment by 0pdd** [comment]
@smallcreep 5 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#19](https://github.com/smallcreep/cucumber-seeds/issues/19), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21) are still not solved.

**Comment by 0pdd** [comment]
@smallcreep 4 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21) are still not solved; solved: [#19](https://github.com/smallcreep/cucumber-seeds/issues/19).

**Comment by 0pdd** [comment]
@smallcreep 4 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21), [#24](https://github.com/smallcreep/cucumber-seeds/issues/24) are still not solved; solved: [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#19](https://github.com/smallcreep/cucumber-seeds/issues/19).

**Comment by 0pdd** [comment]
@smallcreep 2 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21) are still not solved; solved: [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#19](https://github.com/smallcreep/cucumber-seeds/issues/19), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#24](https://github.com/smallcreep/cucumber-seeds/issues/24).

**Comment by 0pdd** [comment]
@smallcreep 5 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21), [#33](https://github.com/smallcreep/cucumber-seeds/issues/33), [#34](https://github.com/smallcreep/cucumber-seeds/issues/34), [#35](https://github.com/smallcreep/cucumber-seeds/issues/35) are still not solved; solved: [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#19](https://github.com/smallcreep/cucumber-seeds/issues/19), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#24](https://github.com/smallcreep/cucumber-seeds/issues/24).

**Comment by 0pdd** [comment]
@smallcreep 5 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21), [#34](https://github.com/smallcreep/cucumber-seeds/issues/34), [#35](https://github.com/smallcreep/cucumber-seeds/issues/35), [#41](https://github.com/smallcreep/cucumber-seeds/issues/41) are still not solved; solved: [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#19](https://github.com/smallcreep/cucumber-seeds/issues/19), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#24](https://github.com/smallcreep/cucumber-seeds/issues/24), [#33](https://github.com/smallcreep/cucumber-seeds/issues/33).

**Comment by 0pdd** [comment]
@smallcreep 5 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21), [#34](https://github.com/smallcreep/cucumber-seeds/issues/34), [#41](https://github.com/smallcreep/cucumber-seeds/issues/41), [#48](https://github.com/smallcreep/cucumber-seeds/issues/48) are still not solved; solved: [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#19](https://github.com/smallcreep/cucumber-seeds/issues/19), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#24](https://github.com/smallcreep/cucumber-seeds/issues/24), [#33](https://github.com/smallcreep/cucumber-seeds/issues/33), [#35](https://github.com/smallcreep/cucumber-seeds/issues/35).

**Comment by 0pdd** [comment]
@smallcreep 5 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21), [#34](https://github.com/smallcreep/cucumber-seeds/issues/34), [#41](https://github.com/smallcreep/cucumber-seeds/issues/41), [#50](https://github.com/smallcreep/cucumber-seeds/issues/50) are still not solved; solved: [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#19](https://github.com/smallcreep/cucumber-seeds/issues/19), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#24](https://github.com/smallcreep/cucumber-seeds/issues/24), [#33](https://github.com/smallcreep/cucumber-seeds/issues/33), [#35](https://github.com/smallcreep/cucumber-seeds/issues/35), [#48](https://github.com/smallcreep/cucumber-seeds/issues/48).

**Comment by 0pdd** [comment]
@smallcreep 3 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21), [#41](https://github.com/smallcreep/cucumber-seeds/issues/41) are still not solved; solved: [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#19](https://github.com/smallcreep/cucumber-seeds/issues/19), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#24](https://github.com/smallcreep/cucumber-seeds/issues/24), [#33](https://github.com/smallcreep/cucumber-seeds/issues/33), [#34](https://github.com/smallcreep/cucumber-seeds/issues/34), [#35](https://github.com/smallcreep/cucumber-seeds/issues/35), [#48](https://github.com/smallcreep/cucumber-seeds/issues/48), [#50](https://github.com/smallcreep/cucumber-seeds/issues/50).

**Comment by 0pdd** [comment]
@smallcreep 2 puzzles [#17](https://github.com/smallcreep/cucumber-seeds/issues/17), [#21](https://github.com/smallcreep/cucumber-seeds/issues/21) are still not solved; solved: [#18](https://github.com/smallcreep/cucumber-seeds/issues/18), [#19](https://github.com/smallcreep/cucumber-seeds/issues/19), [#20](https://github.com/smallcreep/cucumber-seeds/issues/20), [#24](https://github.com/smallcreep/cucumber-seeds/issues/24), [#33](https://github.com/smallcreep/cucumber-seeds/issues/33), [#34](https://github.com/smallcreep/cucumber-seeds/issues/34), [#35](https://github.com/smallcreep/cucumber-seeds/issues/35), [#41](https://github.com/smallcreep/cucumber-seeds/issues/41), [#48](https://github.com/smallcreep/cucumber-seeds/issues/48), [#50](https://github.com/smallcreep/cucumber-seeds/issues/50).

**Comment by 0pdd** [comment]
@smallcreep 2 puzzles [#102](https://github.com/smallcreep/seeds-cucumber/issues/102), [#103](https://github.com/smallcreep/seeds-cucumber/issues/103) are still not solved.
