### ISSUE TITLE
Add DatabaseXML class.

### ISSUE THREAD

**Issue by smallcreep** [smallcreep/seeds-cucumber#122]
Class was envelope database and return TableXML envelope returned Table.

**Comment by smallcreep** [comment]
Blocked #123

**Comment by smallcreep** [comment]
Blocked #125

**Comment by 0pdd** [comment]
@smallcreep 2 puzzles [#128](https://github.com/smallcreep/seeds-cucumber/issues/128), [#129](https://github.com/smallcreep/seeds-cucumber/issues/129) are still not solved.

**Comment by 0pdd** [comment]
@smallcreep all 2 puzzles are solved here: [#128](https://github.com/smallcreep/seeds-cucumber/issues/128), [#129](https://github.com/smallcreep/seeds-cucumber/issues/129).
