### ISSUE TITLE
Add DatabaseXML to RwDefaultItCase

### ISSUE THREAD

**Issue by smallcreep** [smallcreep/seeds-cucumber#133]
In `RwDefaultItCase` don't use `DatabaseXML` need add this class to it.

**Comment by 0pdd** [comment]
@smallcreep 4 puzzles [#135](https://github.com/smallcreep/seeds-cucumber/issues/135), [#136](https://github.com/smallcreep/seeds-cucumber/issues/136), [#137](https://github.com/smallcreep/seeds-cucumber/issues/137), [#138](https://github.com/smallcreep/seeds-cucumber/issues/138) are still not solved.

**Comment by 0pdd** [comment]
@smallcreep 3 puzzles [#136](https://github.com/smallcreep/seeds-cucumber/issues/136), [#137](https://github.com/smallcreep/seeds-cucumber/issues/137), [#138](https://github.com/smallcreep/seeds-cucumber/issues/138) are still not solved; solved: [#135](https://github.com/smallcreep/seeds-cucumber/issues/135).

**Comment by 0pdd** [comment]
@smallcreep 2 puzzles [#137](https://github.com/smallcreep/seeds-cucumber/issues/137), [#138](https://github.com/smallcreep/seeds-cucumber/issues/138) are still not solved; solved: [#135](https://github.com/smallcreep/seeds-cucumber/issues/135), [#136](https://github.com/smallcreep/seeds-cucumber/issues/136).

**Comment by 0pdd** [comment]
@smallcreep the puzzle [#138](https://github.com/smallcreep/seeds-cucumber/issues/138) is still not solved; solved: [#135](https://github.com/smallcreep/seeds-cucumber/issues/135), [#136](https://github.com/smallcreep/seeds-cucumber/issues/136), [#137](https://github.com/smallcreep/seeds-cucumber/issues/137).

**Comment by 0pdd** [comment]
@smallcreep all 4 puzzles are solved here: [#135](https://github.com/smallcreep/seeds-cucumber/issues/135), [#136](https://github.com/smallcreep/seeds-cucumber/issues/136), [#137](https://github.com/smallcreep/seeds-cucumber/issues/137), [#138](https://github.com/smallcreep/seeds-cucumber/issues/138).
