### ISSUE TITLE
Add ignoring iid column.

### ISSUE THREAD

**Issue by smallcreep** [smallcreep/seeds-cucumber#142]
Add ignoring `iid` column.
Add new interface `Storage` it's a `Iterable<Map<String, String>> `.
Add class StorageWithoutIids with removing `iid` in all maps.

**Comment by 0pdd** [comment]
@smallcreep the puzzle [#147](https://github.com/smallcreep/seeds-cucumber/issues/147) is still not solved.

**Comment by 0pdd** [comment]
@smallcreep the puzzle [#149](https://github.com/smallcreep/seeds-cucumber/issues/149) is still not solved; solved: [#147](https://github.com/smallcreep/seeds-cucumber/issues/147).

**Comment by 0pdd** [comment]
@smallcreep the puzzle [#151](https://github.com/smallcreep/seeds-cucumber/issues/151) is still not solved; solved: [#147](https://github.com/smallcreep/seeds-cucumber/issues/147), [#149](https://github.com/smallcreep/seeds-cucumber/issues/149).

**Comment by 0pdd** [comment]
@smallcreep all 3 puzzles are solved here: [#147](https://github.com/smallcreep/seeds-cucumber/issues/147), [#149](https://github.com/smallcreep/seeds-cucumber/issues/149), [#151](https://github.com/smallcreep/seeds-cucumber/issues/151).
