### ISSUE TITLE
Add new step insert into database table

### ISSUE THREAD

**Issue by smallcreep** [smallcreep/seeds-cucumber#60]
Step:
```gherkin
Given There is row in the table public.test:
    | iid | id              | title                               | value              | md5                             |
    | 1   | #Random#Integer | #Random#String#With(#Timestamp#now) | #Random#String(10) | #Encryption#Md5(#Random#String) |
```

This Step added rows in table `test` in schema `public`.
* iid - is unique id in the tests, doesn't added to table, but by this iid use to other data from this row in another steps;
*  #Random#Integer - generate random integer;
* #Random#String#With(#Timestamp#now) - generate random string and add to end now timestamp;
* #Random#String(10) - generate random string length 10;
* #Encryption#Md5(#Random#String) - encrypt md5 hash from random string.

**Comment by 0pdd** [comment]
@smallcreep 3 puzzles [#62](https://github.com/smallcreep/cucumber-seeds/issues/62), [#63](https://github.com/smallcreep/cucumber-seeds/issues/63), [#64](https://github.com/smallcreep/cucumber-seeds/issues/64) are still not solved.

**Comment by 0pdd** [comment]
@smallcreep 2 puzzles [#62](https://github.com/smallcreep/cucumber-seeds/issues/62), [#63](https://github.com/smallcreep/cucumber-seeds/issues/63) are still not solved; solved: [#64](https://github.com/smallcreep/cucumber-seeds/issues/64).

**Comment by 0pdd** [comment]
@smallcreep 2 puzzles [#85](https://github.com/smallcreep/cucumber-seeds/issues/85), [#86](https://github.com/smallcreep/cucumber-seeds/issues/86) are still not solved; solved: [#62](https://github.com/smallcreep/cucumber-seeds/issues/62), [#63](https://github.com/smallcreep/cucumber-seeds/issues/63), [#64](https://github.com/smallcreep/cucumber-seeds/issues/64).

**Comment by 0pdd** [comment]
@smallcreep the puzzle [#85](https://github.com/smallcreep/cucumber-seeds/issues/85) is still not solved; solved: [#62](https://github.com/smallcreep/cucumber-seeds/issues/62), [#63](https://github.com/smallcreep/cucumber-seeds/issues/63), [#64](https://github.com/smallcreep/cucumber-seeds/issues/64), [#86](https://github.com/smallcreep/cucumber-seeds/issues/86).

**Comment by smallcreep** [comment]
@rultor release tag `0.2.0`

**Comment by smallcreep** [comment]
@rultor release, tag=`0.2.0`
