### ISSUE TITLE
RwDefault.java:43-46: Redesign class constructor. For...

### ISSUE THREAD

**Issue by 0pdd** [smallcreep/seeds-cucumber#62]
The puzzle `60-f9b83fa7` from #60 has to be resolved: 

https://github.com/smallcreep/cucumber-seeds/blob/181850d797141c6c03b7c469ff7250295b52cc9f/seeds-db/src/main/java/com/github/smallcreep/cucumber/seeds/rows/RwDefault.java#L43-L46

The puzzle was created by Ilia Rogozhin on 18-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by smallcreep** [comment]
Blocked #68

**Comment by smallcreep** [comment]
Blocked #70

**Comment by smallcreep** [comment]
@rultor hello

**Comment by 0pdd** [comment]
The puzzle `60-f9b83fa7` has disappeared from the source code, that's why I closed this issue.
