### ISSUE TITLE
Add Surrogate and Placeholder interface for replace values.

### ISSUE THREAD

**Issue by smallcreep** [smallcreep/seeds-cucumber#87]

**Comment by 0pdd** [comment]
@smallcreep the puzzle [#89](https://github.com/smallcreep/cucumber-seeds/issues/89) is still not solved.

**Comment by 0pdd** [comment]
@smallcreep the only puzzle [#89](https://github.com/smallcreep/cucumber-seeds/issues/89) is solved here.
