### ISSUE TITLE
Add PlaceholderEncryptionMd5(%s)

### ISSUE THREAD

**Issue by smallcreep** [smallcreep/seeds-cucumber#94]

**Comment by 0pdd** [comment]
@smallcreep the puzzle [#114](https://github.com/smallcreep/seeds-cucumber/issues/114) is still not solved.

**Comment by 0pdd** [comment]
@smallcreep the only puzzle [#114](https://github.com/smallcreep/seeds-cucumber/issues/114) is solved here.
